management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents
resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 3
  bulkhead:
    instances:
      reserveStockBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 5s
  thread-pool-bulkhead:
    instances:
      reserveStockBulkhead:
        maxThreadPoolSize: 10
        coreThreadPoolSize: 5
        queueCapacity: 20
  retry:
    instances:
      InventoryRetry:
        max-attempts: 3        # total calls = 1 original + 2 retries
        wait-duration: 500ms   # wait before retrying
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
           # replace with your actual exception
  timelimiter:
    instances:
      InventoryTimeout:
        timeout-duration: 5s
        cancel-running-future: true